import matplotlib.pyplot as plt
import numpy

def plot_scatter(control, experimental, control_rep = 0, experimental_rep = 0,
                 log_scale = True):
    """ transit_gui.scatterFunc(), plots scatter plot of TA insertions across two samples.

    I haven't figured out fetch_name() yet, so for the moment I commented out the
    x and y axis labels, which is dumb: FIXME.  Once I fix that, put the function call
    into transit_gui.scatterFunc() so that it may be called interactively or via the GUI.

    Arguments:
    control -- Sample to place on the x-axis, it really does not need to be a control.
    experimental -- Sample for the y-axis.

    Keyword arguments:
    control_rep -- Replicate among the x-axis samples to plot.
    experimental_rep -- Replicate among the y-axis samples to plot.
    log_scale -- Do a log1p() on the values if that will make it easier to read.
    """
    X = control[control_rep, :]
    Y = experimental[experimental_rep, :]
    if log_scale:
        X = numpy.log1p(X)
        Y = numpy.log1p(Y)

    plt.plot(X, Y, "bo")
    plt.title('Scatter plot - Reads at TA sites')
    ## plt.xlabel(transit_tools.fetch_name(datasets[0]))
    ## plt.ylabel(transit_tools.fetch_name(datasets[1]))
    plt.show(block = False)
    return plt

## Yanked from qcDisplay.py -- which has a weird comment block at the top saying it was generated by
## wx Formbuilder?  Well, I just want the plotting function to play with.
def sample_ta_histogram(sample, replicate = 0, log_scale = True,
                        color = 'c', alpha = 0.75, bins = 100):
    """ plot_tools.sample_ta_histogram(), plots reads/TA in a sample.

    Arguments:
    sample -- Sample to place on the x-axis, it really does not need to be a control.

    Keyword arguments:
    replicate -- Replicate from a given sample to plot.  Ideally, if None it will do all of them,
    but my python plotting skills are weak.
    log_scale -- Do a log1p() on the #read values if that will make it easier to read.
    """
    X = sample[replicate, :]
    non_zero = X[X > 0]
    n_non_zero = len(non_zero)
    sorted_non_zero = sorted(non_zero)[:int(n_non_zero * 0.99)]
    if log_scale:
        sorted_non_zero = numpy.log1p(sorted_non_zero)

    plt.hist(non_zero, density = 1, facecolor = color, alpha = alpha, bins = bins)
    plt.title('Scatter plot - Reads at TA sites')
    ## plt.xlabel(transit_tools.fetch_name(datasets[0]))
    ## plt.ylabel(transit_tools.fetch_name(datasets[1]))
    plt.show(block = False)
    return plt
